#define ESP_WIFI_SSID_STA          CONFIG_ESP_WIFI_SSID_STA
#define ESP_WIFI_PASS_STA          CONFIG_ESP_WIFI_PASSWORD_STA
#define ESP_WIFI_SSID_AP           CONFIG_ESP_WIFI_SSID_AP
#define ESP_WIFI_PASS_AP           CONFIG_ESP_WIFI_PASSWORD_AP
#define ESP_WIFI_CHANNEL_AP        CONFIG_ESP_WIFI_CHANNEL_AP
#define MAX_STA_CONN               CONFIG_ESP_MAX_STA_CONN
#define ESP_MAXIMUM_RETRY          CONFIG_ESP_MAXIMUM_RETRY
#define DEFAULT_SCAN_LIST_SIZE     CONFIG_EXAMPLE_SCAN_LIST_SIZE 

#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1

void WIFI_STA_CONNECTION();
void WIFI_AP_CONNECTION();
void WIFI_SCAN();
void WIFI_Reconnect();